language: python
python:
  - "2.7"
env:
  - TOX_ENV=pypy-dj1.7
  - TOX_ENV=py3.4-dj1.7
  - TOX_ENV=py3.3-dj1.7
  - TOX_ENV=py3.2-dj1.7
  - TOX_ENV=py2.7-dj1.7
  - TOX_ENV=pypy3-dj1.7-mysql
  - TOX_ENV=pypy-dj1.7-mysql
  - TOX_ENV=py3.4-dj1.7-mysql
  - TOX_ENV=py2.7-dj1.7-mysql
  - TOX_ENV=pypy-dj1.7-postgres
  - TOX_ENV=py3.4-dj1.7-postgres
  - TOX_ENV=py2.7-dj1.7-postgres
  - TOX_ENV=pypy-dj1.6
  - TOX_ENV=py3.3-dj1.6
  - TOX_ENV=py3.2-dj1.6
  - TOX_ENV=py2.7-dj1.6
  - TOX_ENV=py2.6-dj1.6
  - TOX_ENV=pypy-dj1.5
  - TOX_ENV=py3.3-dj1.5
  - TOX_ENV=py3.2-dj1.5
  - TOX_ENV=py2.7-dj1.5
  - TOX_ENV=py2.6-dj1.5
  - TOX_ENV=pypy-dj1.4
  - TOX_ENV=py2.7-dj1.4
  - TOX_ENV=py2.6-dj1.4
  - TOX_ENV=coverage
install:
  - pip install tox==1.8.1 coveralls==0.4.4
addons:
  postgresql: "9.3"
script:
  - tox -e $TOX_ENV
notifications:
  email: false
branches:
  only:
    - master
after_success:
  coveralls
