# Generated by Django 2.2.16 on 2020-10-10 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actstream', '0003_add_follow_flag'),
        ('actstream', '0002_auto_20160917_1849'),
    ]

    operations = [
    ]
